{% set name = "up" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/akavel/up/archive/v{{ version }}.tar.gz
  sha256: 3ea2161ce77e68d7e34873cc80324f372a3b3f63bed9f1ad1aefd7969dd0c1d1

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - m2-grep  # [win]
  commands:
    - 'up --help 2>&1 | grep -q "Usage: COMMAND | up \[OPTIONS\]"'

about:
  home: https://github.com/akavel/up
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Tool for writing command-line pipes with instant live preview
  dev_url: https://github.com/akavel/up

extra:
  recipe-maintainers:
    - danielnachun
